---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: amq-stunnel
  labels:
    app: stunnel
spec:
  output:
    to:
      kind: "ImageStreamTag"
      name: "amq-stunnel:latest"
  successfulBuildsHistoryLimit: 3
  failedBuildsHistoryLimit: 3
  source:
    git:
      uri: 'https://github.com/piyat/test-proxy.git'
    contextDir: server/build
    type: Git
  strategy:
    dockerStrategy:
      noCache: true
    type: Docker
  triggers:
  - type: ConfigChange
  runPolicy: Serial
