---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: amq-stunnel
  labels:
    app: stunnel
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: image-registry.openshift-image-registry.svc:5000/pa-test/amq-stunnel
